name: Sync accounts

on:
  schedule:
    - cron: '0 0,4,19,22 * * *'
    - cron: '*/15 8-17 * * *'

jobs:
  sync-budgets:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: yarn install --frozen-lockfile
    - run: node ./index.js --token "${{ secrets.YNAB_TOKEN }}" --source "${{ secrets.YNAB_SOURCE }}" --target "${{ secrets.YNAB_TARGET }}"
