name: Sync accounts

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: npm ci
    - run: node ./index.js --token $YNAB_TOKEN --source $YNAB_SOURCE --target $YNAB_TARGET
