name: Sync accounts

on:
  schedule:
    # Scheduler runs on UTC time, so I adjusted these for UTC+3 (Turkish time)
    - cron: '0 1,16,19,21 * * *'
    - cron: '0 5-14 * * *'

jobs:
  sync-budgets:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: yarn install --frozen-lockfile
    - run: node ./index.js --token "${{ secrets.YNAB_TOKEN }}" --source "${{ secrets.YNAB_SOURCE }}" --target "${{ secrets.YNAB_TARGET }}"
